server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #配置Nacos地址
        # 换成nginx的1111端口，做集群
        #server-addr: 192.168.111.144:1111
#        server-addr: 192.168.182.1:8848
        server-addr: 100.113.79.40:8848
#        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'