server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由id，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配路由名
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            # - After=2020-03-01T12:08:15.582+08:00[Asia/Shanghai]
            # - Cookie=username,mihacker
            # - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            # - Method=GET
            # - Query=param, \d+ #要有参数名param,并且值为正数才会跳转路由
            # - Host=**.atguigu.con
            # - Between=2020-03-06T12:08:15.582+08:00[Asia/Shanghai],2020-03-06T12:08:15.582+08:00[Asia/Shanghai]
            # - Before=2020-03-06T12:08:15.582+08:00[Asia/Shanghai]

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/