server:
  port: 9528

spring:
  application:
    name: cloud-alibaba-gateway
  cloud:
    nacos:
      discovery:
        #        server-addr: localhost:8849 #配置Nacos地址
        server-addr: 1.116.186.198:8848 #配置Nacos地址

    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
      routes:
        - id: flask_route1 #路由id 要求唯一
          uri: http://localhost:8901  #真实服务路径
#          uri: lb://sidercar-service-flask  #真实服务路径
          predicates:
            - Path=/sidercar/flask/**   #断言 路径相匹配的进行路由

        - id: flask_route2 #路由id 要求唯一
          uri: http://localhost:8902  #真实服务路径
#          uri: lb://sidercar-service-flask2  #真实服务路径
          predicates:
            - Path=/sidercar/flask/**   #断言 路径相匹配的进行路由